#!/bin/bash
USER="chumbley"
PASSWORD="lol"

CODE=$(pwd)
DATA=$(pwd)
CONTAINER_NAME="fco"
PORT="1234"

docker run -it --rm \
  -v $CODE:/workspace/code \
  -v $DATA:/workspace/data \
  -e USER=$USER \
  -e PASSWORD=$PASSWORD \
  -e PROJECT_NAME=$PROJECT_NAME \
  --name $CONTAINER_NAME \
  chumbleycode/fco:latest \
  bash