#!/bin/bash
USER="chumbley"
PASSWORD="lol"

CODE=$(pwd)
DATA=$(pwd)
CONTAINER_NAME="fco"
PORT="2234"

docker run -d --rm \
  -v $CODE:/home/fco/workspace/code \
  -v $DATA:/home/fco/workspace/data \
  -p $PORT:8787 \
  -e USER=$USER \
  -e PASSWORD=$PASSWORD \
  -e PROJECT_NAME=$PROJECT_NAME \
  --name $CONTAINER_NAME \
  chumbleycode/fco:latest

open http://localhost:$PORT
