#!/bin/bash
USER="chumbley"
PASSWORD="lol"

CODE=$(pwd)
DATA="/Volumes/Share/preprocess/" 
CONTAINER_NAME="fco_browser"
PORT="2233"

docker run -d --rm \
  -v $CODE:/home/rstudio/fco/workspace/code \
  -v $DATA:/home/rstudio/fco/workspace/data \
  -p $PORT:8787 \
  -e USER=$USER \
  -e PASSWORD=$PASSWORD \
  -e PROJECT_NAME=$PROJECT_NAME \
  --name $CONTAINER_NAME \
  chumbleycode/fco:latest

open http://localhost:$PORT
